    - name: Check a valid IPv4 address
      ansible.builtin.set_fact:
        is_formateada: "{{ IP is ansible.utils.ipv4 }}"
    
    - name: Check a public IP address
      ansible.builtin.set_fact:
        is_public: "{{ IP is ansible.utils.public }}"

    - name: Verificar Si la IP esta en una lista
      ansible.builtin.set_fact:
        is_in_list:  "{{ IP in lista_ips }}" 

    - name: armar mensaje
      ansible.builtin.set_fact:
        message: >
          {% if is_formateada and is_public and is_in_list %}
            The IP {{ IP }} is formateada, public, and in the list!
          {% elif is_formateada and is_public %}
            The IP {{ IP }} is formateada and public.
          {% elif is_formateada and is_in_list %}
            The IP {{ IP }} is private and in the list.
          {% elif is_public and is_in_list %}
            The IP {{ IP }} is public and in the list.
          {% elif is_formateada %}
            The IP {{ IP }} is private.
          {% elif is_public %}
            The IP {{ IP }} is public.
          {% elif is_in_list %}
            The IP {{ IP }} is in the list.
          {% else %}
            The IP {{ IP }} does not meet any conditions.
          {% endif %}
      
    - name: Guardar la salida en un archivo temporal
      lineinfile:
          line: "{{ IP }}: {{  message }}"
          path: /tmp/command_output.txt
          create: yes
      delegate_to: localhost