---
  - name: "Configuracion Base"
    hosts: all
    
    tasks:

      - name: Configurar archivo de sitio
        template:
          src: templates/serverconfig.j2
          dest: "/home/abonino/server.conf"
        vars:
          data: "{{ lookup('fie', './data/webserver1.yaml') }}" 