---
  - name: "Configuracion Base"
    hosts: all
    become: true
    
    tasks:

      - name: cargar variables de un archivo
        include_vars:
          file: data/{{ ansible_hostname }}.yaml

      - name: Configurar archivo de sitio
        template:
          src: templates/serverconfig.j2
          dest: "/home/abonino/server.conf"
       