- name: Añadir usuario al grupo sudo en Debian/Ubuntu
  hosts: all
  become: yes
 
 
  tasks:

    - name: Convertir la lista de usuarios en una lista de Ansible
      set_fact:
        lista_de_usuarios: "{{ usuarios.split(',') }}"

    - name: agregar usuario de sudo
      include_tasks: tareas_sudo.yml
      loop: "{{ lista_de_usuarios }}"