- name: Crear Varios Usuarios
  hosts: all
  become: yes
  
  tasks:
    - name: Obtener información del sistema
      command: cat /etc/os-release
      register: os_release

    - name: Verificar la distribución
      set_fact:
        is_redhat: "{{ 'Red Hat' in os_release.stdout or 'CentOS' in os_release.stdout or 'Fedora' in os_release.stdout }}"
        is_debian: "{{ 'Ubuntu' in os_release.stdout or 'Debian' in os_release.stdout }}"

    - name: Convertir la lista de usuarios en una lista de Ansible
      set_fact:
        lista_de_usuarios: "{{ usuarios.split(',') }}"

    - name: Generar hash de la contraseña 
      command: "openssl passwd -1 {{ item }}"
      loop: "{{ lista_de_usuarios }}"
      register: passwords
      delegate_to: localhost

    - name: Crear usuarios
      user:
        name: "{{ item }}"
        password: "{{ (passwords.results | selectattr('item', 'equalto', item) | first).stdout }}"
        state: present
      loop: "{{ lista_de_usuarios }}"

    - name: Save playbook output to file
      copy:
        content: "{{ playbook_output.stdout }}"
        dest: /tmp/playbook_output.txt
      delegate_to: localhost  

    - name: Enviar mail
      include_tasks: enviar_Salida.yml