- name: Crear Varios Usuarios
  hosts: all
  become: yes
  
  tasks:
    - name: Obtener información del sistema
      command: cat /etc/os-release
      register: os_release

    - name: Verificar la distribución
      set_fact:
        is_redhat: "{{ 'Red Hat' in os_release.stdout or 'CentOS' in os_release.stdout or 'Fedora' in os_release.stdout }}"
        is_debian: "{{ 'Ubuntu' in os_release.stdout or 'Debian' in os_release.stdout }}"

    - name: Convertir la lista de usuarios en una lista de Ansible
      set_fact:
        lista_de_usuarios: "{{ usuarios.split(',') }}"

    - name: Generar hash de la contraseña con openssl
      command: "openssl passwd -1 '{{ item }}'"
      register: hashed_password_output
      loop: "{{ lista_de_usuarios }}"
      delegate_to: localhost


    - name: Crear el usuario si no existe
      user:
        name: "{{ item }}"
        password: "{{ hashed_password_output.stdout }}"
        state: present
      loop: "{{ lista_de_usuarios }}"
