- name: Obtener informaci칩n del sistema
  command: cat /etc/os-release
  register: os_release

- name: Verificar la distribuci칩n
  set_fact:
    is_redhat: "{{ 'Red Hat' in os_release.stdout or 'CentOS' in os_release.stdout or 'Fedora' in os_release.stdout }}"
    is_debian: "{{ 'Ubuntu' in os_release.stdout or 'Debian' in os_release.stdout }}"

- name: Verificar si el usuario existe
  command: getent passwd '{{ item }}'
  register: user_check
  failed_when: false
  changed_when: false

- name: A침adir usuario al grupo wheel en Red Hat
  user:
    name: "{{ item }}"
    groups: wheel
    append: yes
  when: 
    - is_redhat
    - user_check.rc == 0 

- name: A침adir usuario al grupo sudo en Debian/Ubuntu
  user:
    name: "{{ item }}"
    groups: sudo
    append: yes
  when: 
    - is_debian
    - user_check.rc == 0 