- name: Sending an e-mail using Gmail SMTP servers
  hosts: localhost
  gather_facts: no

  tasks:
      - name: Leer contenido del archivo temporal
        slurp:
          src: "{{ path_salida }}"
        register: file_content

      - name: enviar mail
        community.general.mail:
          host: smtp.gmail.com
          port: 587
          username: reportes.automatizados@gmail.com
          password: dgmgnirbrcrttphr
          to: Adrian Bonino <adrian.bonino@la.logicalis.com>
          subject: Ansible-report
          body: "Listado de horas:

            {{ file_content['content'] | b64decode }}
            salida del PLAYBOOK:
            {{ ansible_job_output }}"



        delegate_to: localhost
