---
- name: Configurar y reiniciar SELinux
  hosts: WebDesarrollo
  become: yes
  tasks:

    - name: Obtener el modo SELinux actual
      command: getenforce
      register: selinux_mode

    - name: Mostar el modo SELinux actual
      debug:
        var: selinux_mode.stdout  
    
    - name: Establecer SELinux en modo enforcing
      ansible.posix.selinux:
        state: enforcing
        policy: targeted
      when: selinux_mode.stdout != 'disabled'
      register: selinux_result

    - name: Establecer SELinux en modo permissive
      ansible.posix.selinux:
        state: permissive
      when: selinux_mode.stdout  == 'permissive'
      register: selinux_result

    - name: Establecer SELinux en modo disabled
      ansible.posix.selinux:
        state: disabled
      when: selinux_mode.stdout  == 'disabled'
      register: selinux_result

    - name: Reiniciar el sistema si SELinux está en modo disabled
      ansible.builtin.reboot:
        reboot_timeout: 300
      when: selinux_mode.stdout  == 'disabled'
      # Asegúrate de que no estás en modo `debug`, ya que `reboot` podría requerir una espera o confirmación

      
