---
- name: Procesar lista de IPs
  hosts: localhost
  gather_facts: no
  vars:
    output_file: "/tmp/salida.txt"

  tasks:
    - name: Separar la lista de IPs en una lista de Python
      set_fact:
        ips: "{{ ip_list.split(',') | map('trim') }}"

    - name: Mostrar cada IP de la lista
      debug:
        msg: "IP: {{ item }}"
      loop: "{{ ips }}"

    - name: Verificar IPs y generar líneas para el archivo de salida
      set_fact:
        invalid_ips: "{{ invalid_ips | default([]) }}"
      loop: "{{ ip_list }}"
      loop_control:
        loop_var: ip
      when: not ip | ipaddr('address')
      vars:
        line: "La IP '{{ ip }}' no es válida."
      tasks:
        - name: Agregar línea al archivo de salida
          lineinfile:
            path: "{{ output_file }}"
            line: "{{ line }}"
          delegate_to: localhost



    - name: Leer contenido del archivo
      slurp:
        path: /tmp/archivo.txt
      register: archivo_contenido

    - name: Mostrar contenido del archivo
      debug:
        msg: "Contenido del archivo: {{ archivo_contenido.content | b64decode }}"  
  