---
- name: Procesar lista de IPs
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Separar la lista de IPs en una lista de Python
      set_fact:
        ips: "{{ ip_list.split(',') | map('trim') }}"

    - name: Mostrar cada IP de la lista
      debug:
        msg: "IP: {{ item }}"
      loop: "{{ ips }}"

    - name: Verificar formato de IPs y agregar comentario en un archivo 
      block:
        - name: Verificar formaro de IPs
          assert:
            that:
              - item | "{{ IP is ansible.utils.ipv4 }}"
            fail_msg: "La IP '{{ item }}' está mal escrita."
          loop: "{{ ips }}"
          loop_control:
            loop_var: item
        - name: Agregar línea al archivo si se encuentra una IP mal escrita
          lineinfile:
            path: /tmp/archivo.txt
            line: "IP mal escrita: {{ item }}"
            insertafter: EOF
          loop: "{{ ips }}"
          loop_control:
            loop_var: item
          when: not item | ipaddr  # Solo ejecutar si la IP está mal escrita
      rescue:
        - debug:
            msg: "Se encontró una IP mal escrita."

    - name: Leer contenido del archivo
      slurp:
        path: /tmp/archivo.txt
      register: archivo_contenido

    - name: Mostrar contenido del archivo
      debug:
        msg: "Contenido del archivo: {{ archivo_contenido.content | b64decode }}"  
  