---
- name: Procesar lista de IPs
  hosts: localhost
  gather_facts: no
  vars:
    output_file: "/tmp/salida.txt"

  tasks:
    - name: crear archivo
      lineinfile:
        line: "Salia del comando Block IPs"
        path: /tmp/command_output.txt
        create: yes
    
    - name: Separar la lista de IPs en una lista de Python
      ansible.builtin.set_fact:
        ips: "{{ ip_list.split(',') | map('trim') }}"

    #- name: Mostrar cada IP de la lista
    #  debug:
    #    msg: "IP: {{ item }}"
    #  loop: "{{ ips }}"

    - name: verificar formatos de las ips
      block:
         - name: verificar formato de ips
           ansible.builtin.set_fact:
             #is_formateada: "{{ item is ansible.utils.ipv4 }}"
             is_formateada: "{{ item | ipaddr }}"
         - name: agregar linea al archivo si la Ip es falsa
           lineinfile:
              line: "{{ item }}: no es una ip valida"
              path: /tmp/command_output.txt
           when: not is_formateada
      with_items: "{{ ips }}"
      loop_control:
        loop_var: item

    - name: Leer contenido del archivo
      slurp:
        path: /tmp/archivo.txt
      register: archivo_contenido

    - name: Mostrar contenido del archivo
      debug:
        msg: "Contenido del archivo: {{ archivo_contenido.content | b64decode }}"  
  