---
- name: Procesar lista de IPs
  hosts: localhost
  gather_facts: no
  # vars:
  #   ip_list: "{{ ip_list }}"
  tasks:
    - name: Separar la lista de IPs en una lista de Python
      set_fact:
        ips: "{{ ip_list.split(',')   | map('trim')  }}"
    
    - name: Crear la lista de resultados de IP
      set_fact:
        ip_results: []

    - name: Validar y clasificar IPs
      set_fact:
        ip_result:
          ip: "{{ item }}"
          is_valid: "{{ item | ipaddr }}"
          type: "{{ 'privada' if item | ipaddr | ipaddr('private') else 'pública' if item | ipaddr | ipaddr('public') else 'desconocida' }}"
      loop: "{{ ips }}"
      loop_control:
        loop_var: item_ip
      register: results

    - name: Filtrar resultados válidos
      set_fact:
        ip_results: "{{ ip_results + [item] }}"
      loop: "{{ results.results }}"
      loop_control:
        loop_var: item
      when: item.item_ip != '' and item.ip_result.is_valid

    - name: Mostrar resultados
      debug:
        msg: "IP: {{ item.ip }} - Válida: {{ item.is_valid }} - Tipo: {{ item.type }}"
      loop: "{{ ip_results }}"