---
- name: Extract IPv4 addresses from JSON
  hosts: localhost
  gather_facts: no

  vars:
    json_file: "group_data.json"  # Cambia esto por la ruta de tu archivo JSON

  tasks:
    - name: Leer el archivo JSON
      ansible.builtin.slurp:
        src: "{{ json_file }}"
      register: json_content

    - name: Convertir el contenido a JSON
      ansible.builtin.set_fact:
        data: "{{ json_content.content | b64decode | from_json }}"

    - name: Extraer las direcciones IPv4
      ansible.builtin.set_fact:
        ipv4_addresses: "{{ data.msg.ansible_facts.group.members | map(attribute='ipv4-address') | list }}"

    - name: Mostrar las direcciones IPv4
      ansible.builtin.debug:
        msg: "{{ ipv4_addresses }}"

