---
- name: Check if IP is in the banned list
  hosts: localhost
  vars:
    banned_ips_file: group_data.json
    ip_to_check: "65.49.1.58"
  tasks:
    - name: Load banned IPs
      include_vars:
        file: "{{ banned_ips_file }}"
        name: banned_data

    - name: Check if the IP is banned
      set_fact:
        is_banned: "{{ ip_to_check in banned_ips_list }}"
      vars:
        banned_ips_list: "{{ banned_data.msg.ansible_facts.group.members | map(attribute='ipv4-address') | list }}"

    - name: Display the result
      debug:
        msg: >
          The IP {{ ip_to_check }} is 
          {% if is_banned %} banned {% else %} not banned {% endif %}.
