---
- name: verificacion de IPs - Format
  hosts: all
  become: true

  tasks:
    - name: Check if 10.0.0.0/8 is a valid IPv4 address
      ansible.builtin.set_fact:
        data: "{{ IP is ansible.utils.ipv4 }}"
      delegate_to: localhost
    
    - name: mostrar salida 
      debug:
        var: data
      delegate_to: localhost
