---
- name: verificacion de IPs - Format
  hosts: localhost
  become: true

  tasks:
    - name: Check a valid IPv4 address
      ansible.builtin.set_fact:
        private: "{{ IP is ansible.utils.ipv4 }}"
    
    # - name: mostrar private 
    #   debug: 
    #     var: private
       
    - name: Check a public IP address
      ansible.builtin.set_fact:
        public: "{{ IP is ansible.utils.public }}"

    # - name: mostrar public 
    #   debug: 
    #     var: public

    - name: Verificar Si la IP esta en una lista
      ansible.builtin.set_fact:
        ip_en_lista: " {{ IP in lista_ips }} "
      vars:
        lista_ips:
          - 51.34.1.1
          - 51.34.2.2
          - 51.35.2.2

    - name: mostrar ip_en_lista 
      debug: 
        var: ip_en_lista 

    # - set_fact:
    #     ip_en_lista: "{{ ip_en_lista | bool }}"
    - name: mostrar ip_en_lista 
      debug: 
        var: ip_en_lista   
          
    - name: mostrar salida 
      debug: 
        msg: "La IP tiene un formato valido y es publica"
      when: private and public 

    - name: mostrar si esta en la lista 
      debug: 
        msg: "La IP esta en la lista de IPs "
      when: ip_en_lista == " True"
      