---
- name: verificacion de IPs - Format
  hosts: localhost
  become: true

  tasks:
    - name: Check if 10.0.0.0/8 is a valid IPv4 address
      ansible.builtin.set_fact:
        private: "{{ IP is ansible.utils.ipv4 }}"
      delegate_to: localhost

    - name: Check if 8.8.8.8 is a public IP address
      ansible.builtin.set_fact:
        public: "{{ IP is ansible.utils.public }}"
    
    - name: mostrar salida 
      debug: 
        msg: "La IP tiene un formato valido y es publica"
      when: private AND public 
      delegate_to: localhost
