---
- name: verificacion de IPs - Format
  hosts: localhost
  become: true

  tasks:
    - name: Check a valid IPv4 address
      ansible.builtin.set_fact:
        private: "{{ IP is ansible.utils.ipv4 }}"
      
    - name: Check a public IP address
      ansible.builtin.set_fact:
        public: "{{ IP is ansible.utils.public }}"
          
    - name: mostrar salida 
      debug: 
        msg: "La IP tiene un formato valido y es publica"
      when: private AND public 
      