---
- name: Deploy app Instituto
  hosts: WebProduccion
  gather_facts: no

  tasks:
    - name: Separar la lista de Archivos ingresados en una lista de Python
      ansible.builtin.set_fact:
        files: "{{ files_list.split('\n') | map('trim') }}"
      delegate_to: localhost
    
    - name: Mostrar resultados
      debug:
        msg: "file: {{ item }}"
      loop: "{{ files }}"
      delegate_to: localhost

    - name: Copiar archivos a producccion
      synchronize: 
        src: root@10.54.118.2:{{ item }}
        dest: {{ item }} 
        mode: pull
        rsync_opts:
          - "--rsh='ssh -p 22'"
      loop: "{{ files }}"
      