---
- name: Deploy app Instituto
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Separar la lista de Archivos ingresados en una lista de Python
      ansible.builtin.set_fact:
        ips: "{{ ip_list.split('\n') | map('trim') }}"
      delegate_to: localhost
    
    - name: Mostrar resultados
      debug:
        msg: "IP: {{ item.ip }} - Válida: {{ item.is_valid }} - Tipo: {{ item.type }}"
      loop: "{{ ip_results }}"
      delegate_to: localhost