---
- name: Deploy app Instituto
  hosts: WebProduccion
  gather_facts: no
  become: yes
  vars:
    file_path: "/var/www/html/V1/instituto/scr/BCP/Internet/dir1/recursos/file1.php"

  tasks:

    - name: Separar la ruta del archivo
      set_fact:
        parts: "{{ file_path | split('/') }}"

    - name: Separar la ruta del archivo en el directorio y el nombre del archivo
      set_fact:
        directory_path: "{{ parts[:-1] | join('/') }}"
        file_name: "{{ parts[-1] }}"

    - name: Verificar si el directorio existe
      stat:
        path: {{ directory_path }}
      register: directorio_existente    
    
    - name: Crear el directorio si no existe
      file:
        path: {{ directory_path }}
        state: directory
      when: not directorio_existente.stat.exists
    
    - name: Mostrar el directorio y el nombre del archivo
      debug:
        msg:
          - "Directorio: {{ directory_path }}"
          - "Nombre del archivo: {{ file_name }}"