---
- name: Deploy app Instituto
  hosts: localhost
  gather_facts: no
  become: yes
  vars:
    file_path: "/var/www/html/V1/instituto/scr/BCP/Internet/dir1/file1.php"

  tasks:
    - name: Separar la ruta del archivo en el directorio y el nombre del archivo
      set_fact:
        parts: "{{ file_path | split('/') }}"
        directory_path: "{{ parts[:-1] | join('/') }}"
        file_name: "{{ parts[-1] }}"
    
    - name: Mostrar el directorio y el nombre del archivo
      debug:
        msg:
          - "Directorio: {{ directory_path }}"
          - "Nombre del archivo: {{ file_name }}"