---
- name: Verificar si todos los archivos existen de Desarrollo
  hosts: all
  gather_facts: no
  become: yes
   
  tasks:
    
    - name: Separar la lista de Archivos ingresados en una lista de Python
      ansible.builtin.set_fact:
        files: "{{ files_list.split('\n') | map('trim') }}"
      delegate_to: localhost
             
    - name: Verificar si los archivos existen en el servidor de desarrollo
      ansible.builtin.stat:
        path: "{{ item }}"
      register: stat_result
      loop: "{{ files }}"
      delegate_to: 10.54.118.2
    
    - name: Crear lista de archivos existentes
      set_fact:
        existing_files: "{{ stat_result.results | selectattr('stat.exists', 'equalto', True) | map(attribute='item') | list }}"
      delegate_to: localhost

    - name: Mostrar archivos que existen en el host fuente
      debug:
        msg: "Archivo '{{ item }}' existe en el host fuente"
      loop: "{{ existing_files }}"
      delegate_to: localhost

    - name: Separar la ruta del archivo
      set_fact:
        parts: "{{ items | split('/') | list }}"
      loop: "{{ existing_files }}"
      delegate_to: localhost

    - name: Separar la ruta del archivo en el directorio y el nombre del archivo
      set_fact:
        directories_path: "{{ parts[:-1] | join('/') | list }}"
      loop: "{{ existing_files }}"
      delegate_to: localhost

    - name: Mostrar archivos que existen en el host fuente
      debug:
        msg: "Directorio: '{{ item }}' "
      loop: "{{ existing_files }}"
      delegate_to: localhost

    
        

    