---
- name: Verificar si todos los archivos existen de Desarrollo
  hosts: WebDesarrollo
  gather_facts: no
  become: yes
   
  tasks:
    
    - name: Separar la lista de Archivos ingresados en una lista de Python
      ansible.builtin.set_fact:
        files: "{{ files_list.split('\n') | map('trim') }}"
      delegate_to: localhost
             
    - name: Verificar si los archivos existen en el servidor de desarrollo
      ansible.builtin.stat:
        path: "{{ item }}"
      register: stat_result
      loop: "{{ files }}"
    
    - name: Crear lista de archivos existentes
      set_fact:
        existing_files: "{{ stat_result.results | selectattr('stat.exists', 'equalto', True) | map(attribute='item') | list }}"
      delegate_to: localhost

    - name: Crear archivo de varible
      copy:
        content: |
          existing_files:
          {% for file_path in existing_files %}
            - "{{ file_path }}"
          {% endfor %}
        dest: /tmp/existing_files.yml
      delegate_to: localhost

    #- name: Guardar la variable en un archivo JSON
    #  copy:
    #    content: |
    #      existing_files:
    #        - "{{ existing_files }}"
    #    dest: /tmp/variable.yml
    #  delegate_to: localhost

    - name: Mostrar archivos que existen en el host fuente
      debug:
        msg: "Archivo '{{ item }}' existe en el host fuente"
      loop: "{{ existing_files }}"
      delegate_to: localhost

- name: Verificar que los directorios existen y sino crearlos
  hosts: WebProduccion
  gather_facts: no
  become: yes

  tasks:

    - name: Leer contenido del archivo
      include_vars: 
        file: /tmp/existing_files.yml
      delegate_to: localhost

    - name: Mostrar contenido del archivo
      debug:
        var: existing_files
      
    - name: Separar la ruta del archivo
      set_fact:
        parts: "{{ item | split('/')  }}"
        directories_path: "{{ parts[:-1] | join('/') | list }}"
      loop: "{{ existing_files }}"

    - name: mostrar listado
      debug:
        var: directories_path