---
- name: Copiar archivo a varios hosts
  hosts: all
  gather_facts: no

  tasks:
    - name: Copiar archivo.txt a los hosts
      copy:
        src: file.config   
        dest: /home/ansible
        # recursive: yes  para copiar directorios completos en forma recursiva