---
- name: Habilitar SELinux de forma permanente
  hosts: WebDesarrollo
  gather_facts: no

  tasks:
    - name: Obtener el modo SELinux actual
      command: getenforce
      register: selinux_mode

    - name: Mostar el modo SELinux actual
      debug:
        var: selinux_mode.stdout 
    
    - name: Modificar SELinux en /etc/selinux/config
      lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: 'SELINUX=disabled'
      when: selinux_mode.stdout == "Permissive" or selinux_mode.stdout == "Enforcing"

    - name: Reiniciar el sistema si SELinux está en modo disabled
      ansible.builtin.reboot:
        reboot_timeout: 300
      when: selinux_mode.stdout == "Permissive" or selinux_mode.stdout == "Enforcing"