- name: Obtener listado de m치quinas virtuales de vCenter
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Obtener informaci칩n de todas las m치quinas virtuales
      community.vmware.vmware_vm_info:
        hostname: "10.54.100.191"
        username: "abonino"
        password: "4d6edd4f9478325a"
        validate_certs: no
      register: vminfo

    - name: Mostrar el listado de m치quinas virtuales
      debug:
        msg: "{{ item.guest_name }}"
      loop: "{{ vminfo.virtual_machines }}"