---
  - name: "Armar un documento con la configuracion horario de los servidores"
    hosts: all
    become: true
    
    tasks:

      - name: consultar confg de horario
        shell: "date"
        register: out_date

      - name: Generar salida
        set_fact:
          salida: "{{ salida|default([]) + [{ 'host': ansible_hostname, 'output': out_date.stdout }] }}"
        delegate_to: localhost

      - name: Mostrar horarios
        debug:
          msg: "{{ salida }}"

      - name: Guardar la salida en un archivo temporal
        copy:
          content: "{{ ansible_hostname }}: {{  out_date.stdout }}"
          dest: /tmp/command_output.txt
          mode: '0644'
          delegate_to: localhost
          run_once: true

  - name: Sending an e-mail using Gmail SMTP servers
    hosts: localhost
    gather_facts: no

    tasks:
      - name: Leer contenido del archivo temporal
        slurp:
          src: /tmp/command_output.txt
        register: file_content

      - name: enviar mail
        community.general.mail:
          host: smtp.gmail.com
          port: 587
          username: reportes.automatizados@gmail.com
          password: lbruwodaqnzpepdb
          to: Adrian Bonino <adrian.bonino@la.logicalis.com>
          subject: Ansible-report
          body: "{{ file_content['content'] | b64decode }}"
        delegate_to: localhost