---
  - name: "Armar un documento con la configuracion horario de los servidores"
    hosts: all
    become: true
    
    tasks:

      - name: consultar confg de horario
        shell: "date"
        register: out_date

      - name: Generar salida
        set_fact:
          salida: "{{ salida|default([]) + [{ 'host': ansible_hostname, 'output': out_date.stdout }] }}"

      - name: Mostrar horarios
        debug:
          msg: "{{ salida }}"

  - name: Sending an e-mail using Gmail SMTP servers
    hosts: localhost
    gather_facts: no

    tasks:
      - name: concatenar salidas
        set_fact:
          full_output: "{{ salida | join('\n') }}"

      - name: enviar mail
        community.general.mail:
          host: smtp.gmail.com
          port: 587
          username: reportes.automatizados@gmail.com
          password: lbruwodaqnzpepdb
          to: Adrian Bonino <adrian.bonino@la.logicalis.com>
          subject: Ansible-report
          body: "{{ full_output }}"
        delegate_to: localhost