---
  - name: "Armar un documento con la configuracion horario de los servidores"
    hosts: all
    become: true
    
    tasks:

      - name: consultar confg de horario
        shell: "date"
        register: out_date

      - name: Generar salida
        set_fact:
          salida: "{{ salida|default([]) + [{ 'host': ansible_hostname, 'output': out_date.stdout }] }}"
        delegate_to: localhost

      - name: Mostrar horarios
        debug:
          msg: "{{ salida }}"