---
- name: "Encuentra el directorio base común en un listado de PATH absolutos"
  hosts: WebDesarrollo
  become: true
  vars:
    files:
      - /var/www/html/v1/intrenet/instituto/file1
      - /var/www/html/v1/intrenet/instituto/file2
      - /var/www/html/v1/intranet/otraclase/fiel4
      - /var/www/html/v1/intranet/instituto/file1
      - /var/www/html/v1/intranet/otraclase/fiel5

  tasks:
    - name: Guardar archivos en un archivo temporal
      copy:
        content: "{{ files | join('\n') }}"
        dest: /tmp/paths.txt

    - name: Ejecutar el script Python para encontrar el prefijo común
      command: python3 ./find_common_prefix.py {{ lookup('file', '/tmp/paths.txt') }}
      register: common_prefix_result

    - name: Mostrar directorio base común
      debug:
        msg: "Directorio base común: {{ common_prefix_result.stdout }}"
