---
- name: "muestra el directorio base de un listado de PATH absolutos"
  hosts: localhost
  become: true
  vars:
      files:
       - /var/www/html/v1/intrenet/instituto/file1
       - /var/www/html/v1/intrenet/instituto/file2
       - /var/www/html/v1/intranet/otraclase/fiel4
       - /var/www/html/v1/intranet/instituto/file1
       - /var/www/html/v1/intranet/otraclase/fiel5
    
  tasks:
    - name: Convertir rutas en listas de directorios
      set_fact:
        dirs_lists: "{{ files | map('split', '/') | list }}"

    - name: Encontrar el prefijo común
      set_fact:
        common_prefix: "{{ dirs_lists[0] | intersect(dirs_lists[1:]) | join('/') }}"
    
    - name: Mostrar directorio base común
      debug:
        msg: "Directorio base común: {{ common_prefix }}"
