---
  - name: "Reemplazar una cadena en un archivo"
    hosts: all
    become: true
    
    vars:
      gmt_time: '-4'
     
    tasks:
    - replace:
        path: "{{ item }}"
        regexp: '-Duser.timezone=GMT-[0-9]'
        replace: '-Duser.timezone=GMT{{ gmt_time }}'
        backup: yes
      loop:
        - /home/abonino/archivo_copia.sh
        - /home/abonino/archivo.txt