---
  - name: "Armar un documento con la configuracion horario de los servidores"
    hosts: all
    
    tasks:

      - name: consultar confg de horario
        shell: "date"
        register: out_date
        when: ansible_facts['os_family'] == 'RedHat'
        
      - name: Ejecutar comando PowerShell para obtener la hora actual
        win_command: powershell -Command "Get-Date -Format 'yyyy-MM-dd HH:mm:ss'"
        register: out_date
        when:  ansible_facts['os_family'] == 'Windows'

      - name: Guardar la salida en un archivo temporal
        lineinfile:
          line: "{{ ansible_hostname }}: {{  out_date.stdout }}"
          path: /tmp/command_output.txt
          create: yes
        delegate_to: localhost

  