---
  - name: "Mail OK"
    hosts: localhost
    become: true
    
    tasks:

      - name: Leer contenido del archivo temporal
        slurp:
          src: /tmp/command_output.txt
        register: file_content

      - name: enviar mail
        community.general.mail:
          host: smtp.gmail.com
          port: 587
          username: reportes.automatizados@gmail.com
          password: lbruwodaqnzpepdb
          to: Adrian Bonino <adrian.bonino@la.logicalis.com>
          subject: Ansible-report
          body: "Listado de horas:

          ----------------------------------------------------------------

          La tarea se realizo correctamente"
        delegate_to: localhost