---
- name: Ejemplo de envío de resultado de playbook por correo
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Ejecutar playbook y registrar la salida
      include_tasks: horas.yml
      register: salida_playbook